name: API Nightly

on:
  schedule:
    - cron: '00 16 * * *'

jobs:
  api_develop:
    uses: ./.github/workflows/api.yml
    with:
      environment: develop

  api_test:
    uses: ./.github/workflows/api.yml
    with:
      environment: test